### ISSUE TITLE
CDN.js

### ISSUE THREAD

**Issue by zenorocha** [PolymerLabs/cdn#1]
I've added Polymer to CDN.js:

```
http://cdnjs.cloudflare.com/ajax/libs/polymer/0.0.20130711/polymer.min.js
```

So I was wondering what is this repo about?

**Comment by Download** [comment]
@sjmiles 
I guess you forgot anyway  :)

@zenorocha 
The CDNJS seems to be outdated. Any plans on updating it?

In the meantime I have set up a CDN for 1.0+ right here on GitHub, which can be used through [RawGit](https://rawgit.com/). It hosts not just Polymer.js but all elements as well so they can be all imported from CDN and transitive dependencies will work.

https://github.com/Download/polymer-cdn

If you guys think this is a good idea and would like to contribute to it, just let me know and I'll add you as contributors.
